// Mocks generated by Mockito 5.4.6 from annotations
// in jawara_pintar_mobile_version/test/dashboard_kegiatan/data/datasources/dashboard_kegiatan_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jawara_pintar_mobile_version/features/dashboard-kegiatan/data/datasources/dashboard_remote_datasource.dart'
    as _i2;
import 'package:jawara_pintar_mobile_version/features/dashboard-kegiatan/domain/entities/kegiatan_entity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DashboardKegiatanRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardKegiatanRemoteDataSource extends _i1.Mock
    implements _i2.DashboardKegiatanRemoteDataSource {
  @override
  _i3.Future<int> getTotalKegiatan() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalKegiatan, []),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Map<String, int>> getKegiatanPerKategori() =>
      (super.noSuchMethod(
            Invocation.method(#getKegiatanPerKategori, []),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
            returnValueForMissingStub: _i3.Future<Map<String, int>>.value(
              <String, int>{},
            ),
          )
          as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<Map<String, int>> getKegiatanBerdasarkanWaktu() =>
      (super.noSuchMethod(
            Invocation.method(#getKegiatanBerdasarkanWaktu, []),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
            returnValueForMissingStub: _i3.Future<Map<String, int>>.value(
              <String, int>{},
            ),
          )
          as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<List<_i4.PenanggungJawabEntity>> getPenanggungJawabTerbanyak() =>
      (super.noSuchMethod(
            Invocation.method(#getPenanggungJawabTerbanyak, []),
            returnValue: _i3.Future<List<_i4.PenanggungJawabEntity>>.value(
              <_i4.PenanggungJawabEntity>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.PenanggungJawabEntity>>.value(
                  <_i4.PenanggungJawabEntity>[],
                ),
          )
          as _i3.Future<List<_i4.PenanggungJawabEntity>>);

  @override
  _i3.Future<List<int>> getKegiatanPerBulan() =>
      (super.noSuchMethod(
            Invocation.method(#getKegiatanPerBulan, []),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);
}
