// Mocks generated by Mockito 5.4.6 from annotations
// in jawara_pintar_mobile_version/test/warga/data/repositories/warga_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:jawara_pintar_mobile_version/features/warga/data/datasources/warga_remote_datasource.dart'
    as _i4;
import 'package:jawara_pintar_mobile_version/features/warga/data/models/keluarga_model.dart'
    as _i3;
import 'package:jawara_pintar_mobile_version/features/warga/data/models/warga_model.dart'
    as _i2;
import 'package:jawara_pintar_mobile_version/features/warga/domain/usecases/filter_warga.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWargaModel_0 extends _i1.SmartFake implements _i2.WargaModel {
  _FakeWargaModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeluargaModel_1 extends _i1.SmartFake implements _i3.KeluargaModel {
  _FakeKeluargaModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WargaRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWargaRemoteDataSource extends _i1.Mock
    implements _i4.WargaRemoteDataSource {
  MockWargaRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.WargaModel>> getAllWarga() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWarga, []),
            returnValue: _i5.Future<List<_i2.WargaModel>>.value(
              <_i2.WargaModel>[],
            ),
          )
          as _i5.Future<List<_i2.WargaModel>>);

  @override
  _i5.Future<_i2.WargaModel> getWargaById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWargaById, [id]),
            returnValue: _i5.Future<_i2.WargaModel>.value(
              _FakeWargaModel_0(this, Invocation.method(#getWargaById, [id])),
            ),
          )
          as _i5.Future<_i2.WargaModel>);

  @override
  _i5.Future<void> createWarga(_i2.WargaModel? warga) =>
      (super.noSuchMethod(
            Invocation.method(#createWarga, [warga]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateWarga(_i2.WargaModel? warga) =>
      (super.noSuchMethod(
            Invocation.method(#updateWarga, [warga]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.WargaModel>> filterWarga(_i6.FilterWargaParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#filterWarga, [params]),
            returnValue: _i5.Future<List<_i2.WargaModel>>.value(
              <_i2.WargaModel>[],
            ),
          )
          as _i5.Future<List<_i2.WargaModel>>);

  @override
  _i5.Future<List<_i3.KeluargaModel>> getAllKeluarga() =>
      (super.noSuchMethod(
            Invocation.method(#getAllKeluarga, []),
            returnValue: _i5.Future<List<_i3.KeluargaModel>>.value(
              <_i3.KeluargaModel>[],
            ),
          )
          as _i5.Future<List<_i3.KeluargaModel>>);

  @override
  _i5.Future<List<_i3.KeluargaModel>> searchKeluarga(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchKeluarga, [query]),
            returnValue: _i5.Future<List<_i3.KeluargaModel>>.value(
              <_i3.KeluargaModel>[],
            ),
          )
          as _i5.Future<List<_i3.KeluargaModel>>);

  @override
  _i5.Future<List<_i3.KeluargaModel>> getAllKeluargaWithRelations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllKeluargaWithRelations, []),
            returnValue: _i5.Future<List<_i3.KeluargaModel>>.value(
              <_i3.KeluargaModel>[],
            ),
          )
          as _i5.Future<List<_i3.KeluargaModel>>);

  @override
  _i5.Future<_i3.KeluargaModel> getKeluargaById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getKeluargaById, [id]),
            returnValue: _i5.Future<_i3.KeluargaModel>.value(
              _FakeKeluargaModel_1(
                this,
                Invocation.method(#getKeluargaById, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.KeluargaModel>);

  @override
  _i5.Future<int> createKeluarga(_i3.KeluargaModel? keluarga) =>
      (super.noSuchMethod(
            Invocation.method(#createKeluarga, [keluarga]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> updateKeluarga(_i3.KeluargaModel? keluarga) =>
      (super.noSuchMethod(
            Invocation.method(#updateKeluarga, [keluarga]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAllRumahSimple() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRumahSimple, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> searchRumah(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchRumah, [query]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<_i2.WargaModel>> getWargaTanpaKeluarga() =>
      (super.noSuchMethod(
            Invocation.method(#getWargaTanpaKeluarga, []),
            returnValue: _i5.Future<List<_i2.WargaModel>>.value(
              <_i2.WargaModel>[],
            ),
          )
          as _i5.Future<List<_i2.WargaModel>>);

  @override
  _i5.Future<void> updateWargaKeluargaId(
    List<int>? wargaIds,
    int? keluargaId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWargaKeluargaId, [wargaIds, keluargaId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
