// Mocks generated by Mockito 5.4.6 from annotations
// in jawara_pintar_mobile_version/test/dashboard_kegiatan/domain/usecases/get_dashboard_kegiatan_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jawara_pintar_mobile_version/core/errors/failure.dart' as _i5;
import 'package:jawara_pintar_mobile_version/features/dashboard-kegiatan/domain/entities/kegiatan_entity.dart'
    as _i6;
import 'package:jawara_pintar_mobile_version/features/dashboard-kegiatan/domain/repositories/dashboard_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DashboardKegiatanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardKegiatanRepository extends _i1.Mock
    implements _i3.DashboardKegiatanRepository {
  MockDashboardKegiatanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DashboardKegiatanEntity>>
  getDashboardKegiatan() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardKegiatan, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.DashboardKegiatanEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.DashboardKegiatanEntity>(
                    this,
                    Invocation.method(#getDashboardKegiatan, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.DashboardKegiatanEntity>>);
}
