// Mocks generated by Mockito 5.4.6 from annotations
// in jawara_pintar_mobile_version/test/pengeluaran/pengeluaran_remote_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i7;

import 'package:jawara_pintar_mobile_version/features/pengeluaran/data/datasources/remote_datasource.dart'
    as _i3;
import 'package:jawara_pintar_mobile_version/features/pengeluaran/data/models/pengeluaran_model.dart'
    as _i5;
import 'package:jawara_pintar_mobile_version/features/pengeluaran/domain/entities/kategori_transaksi.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PengeluaranRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockPengeluaranRemoteDataSourceImpl extends _i1.Mock
    implements _i3.PengeluaranRemoteDataSourceImpl {
  @override
  _i2.SupabaseClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#client),
            ),
            returnValueForMissingStub: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.SupabaseClient);

  @override
  _i4.Future<List<_i5.PengeluaranModel>> getAllPengeluaran() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPengeluaran, []),
            returnValue: _i4.Future<List<_i5.PengeluaranModel>>.value(
              <_i5.PengeluaranModel>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.PengeluaranModel>>.value(
                  <_i5.PengeluaranModel>[],
                ),
          )
          as _i4.Future<List<_i5.PengeluaranModel>>);

  @override
  _i4.Future<_i5.PengeluaranModel?> getPengeluaranById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPengeluaranById, [id]),
            returnValue: _i4.Future<_i5.PengeluaranModel?>.value(),
            returnValueForMissingStub:
                _i4.Future<_i5.PengeluaranModel?>.value(),
          )
          as _i4.Future<_i5.PengeluaranModel?>);

  @override
  _i4.Future<void> createPengeluaran(_i5.PengeluaranModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#createPengeluaran, [model]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePengeluaran(_i5.PengeluaranModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#updatePengeluaran, [model]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePengeluaran(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePengeluaran, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.KategoriEntity>> getKategoriPengeluaran() =>
      (super.noSuchMethod(
            Invocation.method(#getKategoriPengeluaran, []),
            returnValue: _i4.Future<List<_i6.KategoriEntity>>.value(
              <_i6.KategoriEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i6.KategoriEntity>>.value(
                  <_i6.KategoriEntity>[],
                ),
          )
          as _i4.Future<List<_i6.KategoriEntity>>);

  @override
  _i4.Future<String?> uploadBukti(_i7.File? file, {String? oldUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#uploadBukti, [file], {#oldUrl: oldUrl}),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<Map<String, String?>> getNamesByUids(List<String>? uids) =>
      (super.noSuchMethod(
            Invocation.method(#getNamesByUids, [uids]),
            returnValue: _i4.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i4.Future<Map<String, String?>>);
}
