// Mocks generated by Mockito 5.4.6 from annotations
// in jawara_pintar_mobile_version/test/dashboard_kependudukan/data/repositories/dashboard_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jawara_pintar_mobile_version/features/dashboard-kependudukan/data/datasources/dashboard_remote_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DashboardKependudukanRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardKependudukanRemoteDataSource extends _i1.Mock
    implements _i2.DashboardKependudukanRemoteDataSource {
  MockDashboardKependudukanRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> getTotalKeluarga() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalKeluarga, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getTotalPenduduk() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPenduduk, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Map<String, int>> getStatusPenduduk() =>
      (super.noSuchMethod(
            Invocation.method(#getStatusPenduduk, []),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<Map<String, int>> getJenisKelamin() =>
      (super.noSuchMethod(
            Invocation.method(#getJenisKelamin, []),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<Map<String, int>> getPekerjaanPenduduk() =>
      (super.noSuchMethod(
            Invocation.method(#getPekerjaanPenduduk, []),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<Map<String, int>> getPeranDalamKeluarga() =>
      (super.noSuchMethod(
            Invocation.method(#getPeranDalamKeluarga, []),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<Map<String, int>> getAgama() =>
      (super.noSuchMethod(
            Invocation.method(#getAgama, []),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<Map<String, int>> getPendidikan() =>
      (super.noSuchMethod(
            Invocation.method(#getPendidikan, []),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);
}
