// Mocks generated by Mockito 5.4.6 from annotations
// in jawara_pintar_mobile_version/test/mutasi_keluarga/domain/usecases/mutasi_keluarga_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jawara_pintar_mobile_version/core/errors/failure.dart' as _i5;
import 'package:jawara_pintar_mobile_version/features/mutasi-keluarga/domain/entities/mutasi_keluarga.dart'
    as _i6;
import 'package:jawara_pintar_mobile_version/features/mutasi-keluarga/domain/repositories/mutasi_keluarga_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MutasiKeluargaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMutasiKeluargaRepository extends _i1.Mock
    implements _i3.MutasiKeluargaRepository {
  MockMutasiKeluargaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MutasiKeluarga>>>
  getAllMutasiKeluarga() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMutasiKeluarga, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.MutasiKeluarga>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.MutasiKeluarga>>(
                    this,
                    Invocation.method(#getAllMutasiKeluarga, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MutasiKeluarga>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MutasiKeluarga>> getMutasiKeluarga(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMutasiKeluarga, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.MutasiKeluarga>>.value(
                  _FakeEither_0<_i5.Failure, _i6.MutasiKeluarga>(
                    this,
                    Invocation.method(#getMutasiKeluarga, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.MutasiKeluarga>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> createMutasiKeluarga(
    _i6.MutasiKeluarga? mutasi,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMutasiKeluarga, [mutasi]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#createMutasiKeluarga, [mutasi]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, List<dynamic>>>>
  getFormDataOptions() =>
      (super.noSuchMethod(
            Invocation.method(#getFormDataOptions, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, Map<String, List<dynamic>>>
                >.value(
                  _FakeEither_0<_i5.Failure, Map<String, List<dynamic>>>(
                    this,
                    Invocation.method(#getFormDataOptions, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, List<dynamic>>>>);
}
