// Mocks generated by Mockito 5.4.6 from annotations
// in jawara_pintar_mobile_version/test/pemasukan/data/repositories/pemasukan_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:jawara_pintar_mobile_version/features/pemasukan/data/datasources/pemasukan_remote_datasource.dart'
    as _i3;
import 'package:jawara_pintar_mobile_version/features/pemasukan/data/models/pemasukan_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePemasukanModel_0 extends _i1.SmartFake
    implements _i2.PemasukanModel {
  _FakePemasukanModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PemasukanRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPemasukanRemoteDataSource extends _i1.Mock
    implements _i3.PemasukanRemoteDataSource {
  MockPemasukanRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PemasukanModel>> getPemasukanList({
    String? kategoriFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPemasukanList, [], {
              #kategoriFilter: kategoriFilter,
            }),
            returnValue: _i4.Future<List<_i2.PemasukanModel>>.value(
              <_i2.PemasukanModel>[],
            ),
          )
          as _i4.Future<List<_i2.PemasukanModel>>);

  @override
  _i4.Future<_i2.PemasukanModel> getPemasukanDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPemasukanDetail, [id]),
            returnValue: _i4.Future<_i2.PemasukanModel>.value(
              _FakePemasukanModel_0(
                this,
                Invocation.method(#getPemasukanDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.PemasukanModel>);

  @override
  _i4.Future<void> createPemasukan({
    required String? judul,
    required int? kategoriTransaksiId,
    required double? nominal,
    required String? tanggalTransaksi,
    String? buktiFoto,
    required String? keterangan,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPemasukan, [], {
              #judul: judul,
              #kategoriTransaksiId: kategoriTransaksiId,
              #nominal: nominal,
              #tanggalTransaksi: tanggalTransaksi,
              #buktiFoto: buktiFoto,
              #keterangan: keterangan,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePemasukan({
    required int? id,
    required String? judul,
    required int? kategoriTransaksiId,
    required double? nominal,
    required String? tanggalTransaksi,
    String? buktiFoto,
    required String? keterangan,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePemasukan, [], {
              #id: id,
              #judul: judul,
              #kategoriTransaksiId: kategoriTransaksiId,
              #nominal: nominal,
              #tanggalTransaksi: tanggalTransaksi,
              #buktiFoto: buktiFoto,
              #keterangan: keterangan,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePemasukan(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePemasukan, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> uploadBukti(_i5.File? file, {String? oldUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#uploadBukti, [file], {#oldUrl: oldUrl}),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}
