// Mocks generated by Mockito 5.4.6 from annotations
// in jawara_pintar_mobile_version/test/cetak_laporan/cetak_laporan_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:jawara_pintar_mobile_version/features/cetak-laporan/data/datasources/cetak_laporan_remote_datasource.dart'
    as _i4;
import 'package:jawara_pintar_mobile_version/features/cetak-laporan/data/models/laporan_cetak_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLaporanCetakModel_1 extends _i1.SmartFake
    implements _i3.LaporanCetakModel {
  _FakeLaporanCetakModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CetakLaporanRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCetakLaporanRemoteDataSourceImpl extends _i1.Mock
    implements _i4.CetakLaporanRemoteDataSourceImpl {
  @override
  _i2.SupabaseClient get supabaseClient =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseClient),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabaseClient),
            ),
            returnValueForMissingStub: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabaseClient),
            ),
          )
          as _i2.SupabaseClient);

  @override
  _i5.Future<_i3.LaporanCetakModel> getLaporanData({
    required DateTime? tanggalMulai,
    required DateTime? tanggalAkhir,
    required String? jenisLaporan,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLaporanData, [], {
              #tanggalMulai: tanggalMulai,
              #tanggalAkhir: tanggalAkhir,
              #jenisLaporan: jenisLaporan,
            }),
            returnValue: _i5.Future<_i3.LaporanCetakModel>.value(
              _FakeLaporanCetakModel_1(
                this,
                Invocation.method(#getLaporanData, [], {
                  #tanggalMulai: tanggalMulai,
                  #tanggalAkhir: tanggalAkhir,
                  #jenisLaporan: jenisLaporan,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.LaporanCetakModel>.value(
              _FakeLaporanCetakModel_1(
                this,
                Invocation.method(#getLaporanData, [], {
                  #tanggalMulai: tanggalMulai,
                  #tanggalAkhir: tanggalAkhir,
                  #jenisLaporan: jenisLaporan,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.LaporanCetakModel>);
}
