// Mocks generated by Mockito 5.4.6 from annotations
// in jawara_pintar_mobile_version/test/mutasi_keluarga/data/repositories/mutasi_keluarga_repository_implementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jawara_pintar_mobile_version/features/mutasi-keluarga/data/datasources/mutasi_keluarga_datasource.dart'
    as _i3;
import 'package:jawara_pintar_mobile_version/features/mutasi-keluarga/data/models/mutasi_keluarga_models.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMutasiKeluargaModel_0 extends _i1.SmartFake
    implements _i2.MutasiKeluargaModel {
  _FakeMutasiKeluargaModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MutasiKeluargaDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMutasiKeluargaDatasource extends _i1.Mock
    implements _i3.MutasiKeluargaDatasource {
  MockMutasiKeluargaDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.MutasiKeluargaModel>> getAllMutasiKeluarga() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMutasiKeluarga, []),
            returnValue: _i4.Future<List<_i2.MutasiKeluargaModel>>.value(
              <_i2.MutasiKeluargaModel>[],
            ),
          )
          as _i4.Future<List<_i2.MutasiKeluargaModel>>);

  @override
  _i4.Future<_i2.MutasiKeluargaModel> getMutasiKeluarga(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMutasiKeluarga, [id]),
            returnValue: _i4.Future<_i2.MutasiKeluargaModel>.value(
              _FakeMutasiKeluargaModel_0(
                this,
                Invocation.method(#getMutasiKeluarga, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.MutasiKeluargaModel>);

  @override
  _i4.Future<void> createMutasiKeluarga(_i2.MutasiKeluargaModel? mutasi) =>
      (super.noSuchMethod(
            Invocation.method(#createMutasiKeluarga, [mutasi]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getOptionKeluarga() =>
      (super.noSuchMethod(
            Invocation.method(#getOptionKeluarga, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getOptionRumah() =>
      (super.noSuchMethod(
            Invocation.method(#getOptionRumah, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getOptionWarga() =>
      (super.noSuchMethod(
            Invocation.method(#getOptionWarga, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}
