// Mocks generated by Mockito 5.4.6 from annotations
// in jawara_pintar_mobile_version/test/dashboard_keuangan/data/repositories/dashboard_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jawara_pintar_mobile_version/features/dashboard-keuangan/data/datasources/dashboard_remote_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DashboardRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRemoteDataSource extends _i1.Mock
    implements _i2.DashboardRemoteDataSource {
  MockDashboardRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<double> getTotalPemasukanByYear(String? year) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPemasukanByYear, [year]),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<double> getTotalPengeluaranByYear(String? year) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPengeluaranByYear, [year]),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<List<double>> getMonthlyPemasukan(String? year) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyPemasukan, [year]),
            returnValue: _i3.Future<List<double>>.value(<double>[]),
          )
          as _i3.Future<List<double>>);

  @override
  _i3.Future<List<double>> getMonthlyPengeluaran(String? year) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyPengeluaran, [year]),
            returnValue: _i3.Future<List<double>>.value(<double>[]),
          )
          as _i3.Future<List<double>>);

  @override
  _i3.Future<Map<String, double>> getKategoriPemasukanSummary(String? year) =>
      (super.noSuchMethod(
            Invocation.method(#getKategoriPemasukanSummary, [year]),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<Map<String, double>> getKategoriPengeluaranSummary(String? year) =>
      (super.noSuchMethod(
            Invocation.method(#getKategoriPengeluaranSummary, [year]),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<List<String>> getAvailableYears() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableYears, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);
}
