// Mocks generated by Mockito 5.4.6 from annotations
// in jawara_pintar_mobile_version/test/pesan_warga/data/repositories/pesan_warga_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jawara_pintar_mobile_version/features/pesan-warga/data/datasources/pesan_warga_remote.dart'
    as _i3;
import 'package:jawara_pintar_mobile_version/features/pesan-warga/data/models/pesan_warga_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAspirasiModel_0 extends _i1.SmartFake implements _i2.AspirasiModel {
  _FakeAspirasiModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AspirasiRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAspirasiRemoteDataSource extends _i1.Mock
    implements _i3.AspirasiRemoteDataSource {
  MockAspirasiRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.AspirasiModel>> getAllAspirasi() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAspirasi, []),
            returnValue: _i4.Future<List<_i2.AspirasiModel>>.value(
              <_i2.AspirasiModel>[],
            ),
          )
          as _i4.Future<List<_i2.AspirasiModel>>);

  @override
  _i4.Future<_i2.AspirasiModel> getAspirasiById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAspirasiById, [id]),
            returnValue: _i4.Future<_i2.AspirasiModel>.value(
              _FakeAspirasiModel_0(
                this,
                Invocation.method(#getAspirasiById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.AspirasiModel>);

  @override
  _i4.Future<void> addAspirasi(_i2.AspirasiModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#addAspirasi, [model]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.AspirasiModel> updateAspirasi(_i2.AspirasiModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#updateAspirasi, [model]),
            returnValue: _i4.Future<_i2.AspirasiModel>.value(
              _FakeAspirasiModel_0(
                this,
                Invocation.method(#updateAspirasi, [model]),
              ),
            ),
          )
          as _i4.Future<_i2.AspirasiModel>);

  @override
  _i4.Future<void> deleteAspirasi(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAspirasi, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
